import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Manual sidebar for the Introduction module
  introModuleSidebar: [
    {
      type: 'category',
      label: 'Module 0: Introduction to Physical AI',
      items: [
        'module-0-intro-physical-ai/chapter-1-what-is-physical-ai',
        'module-0-intro-physical-ai/chapter-2-humanoid-robotics-landscape',
        'module-0-intro-physical-ai/chapter-3-dev-environment-setup',
      ],
    },
  ],

  // Manual sidebar for the ROS 2 module
  ros2ModuleSidebar: [
    {
      type: 'category',
      label: 'Module 1: The Robotic Nervous System (ROS 2)',
      items: [
        'module-1-ros2-basics/chapter-1-ros2-basics',
        'module-1-ros2-basics/chapter-2-python-agents',
        'module-1-ros2-basics/chapter-3-urdf-humanoids',
      ],
    },
  ],

  // Manual sidebar for the Gazebo/Unity module
  gazeboUnityModuleSidebar: [
    {
      type: 'category',
      label: 'Module 2: The Digital Twin (Gazebo & Unity)',
      items: [
        'module-2-gazebo-unity-sim/chapter-1-gazebo-physics',
        'module-2-gazebo-unity-sim/chapter-2-unity-digital-twins',
        'module-2-gazebo-unity-sim/chapter-3-simulated-sensors',
      ],
    },
  ],

  // Manual sidebar for the Isaac module
  isaacModuleSidebar: [
    {
      type: 'category',
      label: 'Module 3: The AI-Robot Brain (NVIDIA Isaac™)',
      items: [
        'module-3-isaac-ai-brain/chapter-1-isaac-sim-perception',
        'module-3-isaac-ai-brain/chapter-2-isaac-ros-vslam',
        'module-3-isaac-ai-brain/chapter-3-nav2-path-planning',
      ],
    },
  ],

  // Manual sidebar for the VLA module
  vlaModuleSidebar: [
    {
      type: 'category',
      label: 'Module 4: Vision-Language-Action (VLA) with LLMs',
      items: [
        'module-4-vla-llm-robotics/chapter-1-voice-to-action',
        'module-4-vla-llm-robotics/chapter-2-cognitive-planning',
        'module-4-vla-llm-robotics/chapter-3-autonomous-humanoid',
      ],
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
